INSERT INTO
    users(customerNumber, username, email, password)
VALUES
    (
        103,
        'insecureBobolink6',
        'PRSzthm@gmail.com',
        'Qo196EqODjjreL4C3STk'
    ),
(
        112,
        'abjectSheep9',
        'olNYCFf@gmail.com',
        'KtjLqXGOV3XSUJuKSajX'
    ),
(
        114,
        'resolvedTuna4',
        'feICUne@gmail.com',
        'omaWkO8QClzSx6BWonI9'
    ),
(
        119,
        'cheerfulHoopoe8',
        'OvjVExe@gmail.com',
        'PSXaL5DRpW7gYrsyMxlD'
    ),
(
        121,
        'cheerfulVenison2',
        'JMcLTOi@gmail.com',
        'vQhv7ymrhTEe0ZsOtmqn'
    ),
(
        124,
        'gloomyWildfowl0',
        'wBgjQnL@gmail.com',
        'HNRFkBrDHljPBnYcgkXx'
    ),
(
        125,
        'mildCaribou1',
        'lImmgyZ@gmail.com',
        'fuoM0S1qRslXQaw3VfWn'
    ),
(
        128,
        'ferventCrane9',
        'qqRdoUk@gmail.com',
        'qDPsi7pGKhAgz579h8RM'
    ),
(
        129,
        'truthfulSeagull3',
        'seXcePp@gmail.com',
        'PSk2qmZt4S9H0mrVai4W'
    ),
(
        131,
        'eagerHoopoe4',
        'UeGEJmu@gmail.com',
        'KXpsXMLUUyCBwGymMuSZ'
    ),
(
        141,
        'morbidChile5',
        'SIGYYHB@gmail.com',
        'h2ywySwMSEC1rGDzeGzP'
    ),
(
        144,
        'jumpyCaribou8',
        'WHitBQs@gmail.com',
        'dCI4LDByMOpXMgDQ8iOH'
    ),
(
        145,
        'grumpyTeal1',
        'ucowWNT@gmail.com',
        'UNYCgS5uemoT9EdYa32f'
    ),
(
        146,
        'similarOtter5',
        'StaegdS@gmail.com',
        'YUQxrngttEOFvun9Ukvx'
    ),
(
        148,
        'unhappyPonie6',
        'rUOOGgB@gmail.com',
        'NjXHWeVxheyy1sAxwDVU'
    ),
(
        151,
        'decimalGranola3',
        'lnteybz@gmail.com',
        'yEwVEkgC1d3DQkdTSQC6'
    ),
(
        157,
        'stressedWidgeon8',
        'MzRKwmZ@gmail.com',
        '8efgEY3KI1zYvs2RWj7y'
    ),
(
        161,
        'amusedBuzzard3',
        'sNsuwNO@gmail.com',
        'Hkiakty29RqnfLgeDDAn'
    ),
(
        166,
        'peskyLapwing6',
        'bNlgHUk@gmail.com',
        'yCMeobFTWH96sNDm2YW6'
    ),
(
        167,
        'excitedApricots3',
        'ZRFBgmu@gmail.com',
        'FbO5GORCup0o1QoGfxPv'
    ),
(
        168,
        'dejectedEggs3',
        'sNlInzL@gmail.com',
        'cQukU2tKPLYpMCQSMfbF'
    ),
(
        169,
        'sugaryMagpie4',
        'eWFXsrC@gmail.com',
        'JJcJ8VcuBYoWtL2omH3N'
    ),
(
        171,
        'similarSmelt6',
        'DboyAGi@gmail.com',
        '7Isd81cJyWKNYgc9gyaq'
    ),
(
        172,
        'superiorChamois6',
        'VkCRlvM@gmail.com',
        '1P1acMf5RZZ3j1jXUvjf'
    ),
(
        173,
        'fondTeal2',
        'kAsNSxs@gmail.com',
        '879GuswAHAZqSZt1ix0r'
    ),
(
        175,
        'chicRhino3',
        'pGAFDrf@gmail.com',
        'Xzl2EuosdlWGH0KAiSc8'
    ),
(
        177,
        'joyfulOcelot1',
        'pafSNgB@gmail.com',
        'bXvPAevqEcucojaEntlx'
    ),
(
        181,
        'mellowCurlew9',
        'TJALZBg@gmail.com',
        'Jv1zCjUGz0q7qeWAix9W'
    ),
(
        186,
        'shyIguana5',
        'MvRwUBG@gmail.com',
        'ac44HY4srDHkzjGNkMTO'
    ),
(
        187,
        'anxiousWeaver2',
        'TFTFRLj@gmail.com',
        '1ATTZOYbyKduCNpze1rQ'
    ),
(
        189,
        'yearningWeaver3',
        'tnWzJlM@gmail.com',
        'eJrcGKQjqiAcIzdohgmF'
    ),
(
        198,
        'pitifulLlama1',
        'tsIRXsV@gmail.com',
        '0fo2D1WXZMAKtCR5ufjz'
    ),
(
        201,
        'trustingCaribou1',
        'qaqAwmp@gmail.com',
        'K2taUNUDWdEQnvlSRTpc'
    ),
(
        202,
        'culturedChamois4',
        'YVUkYrr@gmail.com',
        'vl4L2wJkUhO7daZ0qmHH'
    ),
(
        204,
        'solidVenison8',
        'XteSwsJ@gmail.com',
        't4gzLT3k3mkXEt5bfKYe'
    ),
(
        205,
        'forsakenLemur4',
        'EcwZnvC@gmail.com',
        '3KrJj04X6vtzltMedxq2'
    ),
(
        206,
        'boastfulPonie4',
        'MwPAGPa@gmail.com',
        '9CNXKf4CrnFA9p71T7AC'
    ),
(
        209,
        'pridefulVenison6',
        'KVzxKsK@gmail.com',
        '9GA62ftG8mywxG7fRxd9'
    ),
(
        211,
        'soreLemur3',
        'nQkzsWM@gmail.com',
        'qrWezYVTaPQhUQjbqqhl'
    ),
(
        216,
        'humorousSheep9',
        'iWtjsIu@gmail.com',
        'Kn7pJVKDwjEvrrtaKWa7'
    ),
(
        219,
        'excitedRat8',
        'vruPcPY@gmail.com',
        '1whXJdoukxyJgIwyasGu'
    ),
(
        223,
        'mereClam2',
        'XZnlYAX@gmail.com',
        'C9k71MHWrft4gpskrphM'
    ),
(
        227,
        'truthfulRelish2',
        'ewMeijR@gmail.com',
        '1TSgtOVZpedWAxwMZ1SM'
    ),
(
        233,
        'thrilledCur6',
        'jwAyhSc@gmail.com',
        'qlrdCPsL7DTd6Ocj29rG'
    ),
(
        237,
        'trustingRat2',
        'sgpqvWs@gmail.com',
        'jGp9exHaDnyLDtcy1LMO'
    ),
(
        239,
        'needfulRat1',
        'xAgyXbh@gmail.com',
        'HVBRBNeHTLf50B2z9uRp'
    ),
(
        240,
        'insecureWildfowl2',
        'mYsSUdk@gmail.com',
        'kkUcTxJa9RB2Wrop1Nnt'
    ),
(
        242,
        'awedCheese8',
        'XofUUkr@gmail.com',
        'UpwAeW1SOqLMWiKga8uP'
    ),
(
        247,
        'sheepishSalami8',
        'yYmSCSE@gmail.com',
        'vB9KRIOLeXQ23O9xti7R'
    ),
(
        249,
        'anxiousQuiche8',
        'WyUUTRY@gmail.com',
        'yYA234qNSlFvvZdIV3Is'
    ),
(
        250,
        'dopeyCow8',
        'YWuQyhY@gmail.com',
        'NxeAJOGtzN9woFpbfyEV'
    ),
(
        256,
        'giddyMallard6',
        'HhijkLx@gmail.com',
        'M05ja1OTGrBwkUbM1hUE'
    ),
(
        259,
        'gloomyBagels0',
        'rdJBslk@gmail.com',
        'N5jEIJ2ozZKhqVjG4utG'
    ),
(
        260,
        'amazedOil7',
        'khAgqXy@gmail.com',
        't4jjyPcZ5JgVBfzfeG5H'
    ),
(
        273,
        'anxiousOcelot7',
        'nJMqbWF@gmail.com',
        'FNdK2rFtu7i6QOSLwY7g'
    ),
(
        276,
        'adoringBustard7',
        'ljcelbY@gmail.com',
        'npgA2RQFLJ7brrk7ZE0d'
    ),
(
        278,
        'thriftyEggs0',
        'PTUvWQm@gmail.com',
        'QS7wDpxuJt06QTBLqRGw'
    ),
(
        282,
        'innocentRice5',
        'hzgSWCW@gmail.com',
        'znmO1i60eMXUeCZKiT83'
    ),
(
        286,
        'ecstaticTuna1',
        'ZSZuMda@gmail.com',
        'J7XGKh3VUwEOjZRlCtuG'
    ),
(
        293,
        'betrayedFish4',
        'SDBOgon@gmail.com',
        '3UNoqIOF7X9H3lWBWNPx'
    ),
(
        298,
        'scornfulPear8',
        'aSxQFAY@gmail.com',
        'r8KWqnMSwRKqy8vFT0As'
    ),
(
        299,
        'shamefulPiglet3',
        'EcQfJzY@gmail.com',
        'dDP7c3K9IacYADlHUhVq'
    ),
(
        303,
        'cynicalAntelope5',
        'iTPBomg@gmail.com',
        '8v7rBtcSo6FvT1RwsHpL'
    ),
(
        307,
        'debonairTortoise2',
        'RtGvfhQ@gmail.com',
        'MOTApAWglmTy9ryAcra2'
    ),
(
        311,
        'exactingMallard4',
        'qSipSfv@gmail.com',
        'GeWM6RwQZQhtvlYKfgyx'
    ),
(
        314,
        'sugaryTuna3',
        'UxkUPwG@gmail.com',
        'QAYULpcdtzxtQPLAKN8G'
    ),
(
        319,
        'superiorRaisins9',
        'gsPkzcL@gmail.com',
        'DtpHeeoNX47kMlcpWfYU'
    ),
(
        320,
        'cockyFerret3',
        'sFkSWth@gmail.com',
        'Bg9JOTZOIXyO0cDiU3hG'
    ),
(
        321,
        'sheepishMeerkat2',
        'GbOzcRH@gmail.com',
        'eyzrOpjcdOR4dfF9erv7'
    ),
(
        323,
        'sadPudding4',
        'BQySBaO@gmail.com',
        'ZlrI6aZn5VxnioApcgvq'
    ),
(
        324,
        'relievedCake6',
        'SIuYVbn@gmail.com',
        '44AD344ReUHx5j1Klvsj'
    ),
(
        328,
        'wingedOatmeal5',
        'acqZkXl@gmail.com',
        'UA96DUu2rJtjN5b9umJB'
    ),
(
        333,
        'puzzledLemur7',
        'oCXaLQE@gmail.com',
        'Z9GDtA2dM6NryIXSxwim'
    ),
(
        334,
        'crummyGnu3',
        'KFmrXhD@gmail.com',
        'wObbNINlRepzllUlnQf3'
    ),
(
        335,
        'alertHyena8',
        'vdgNlAw@gmail.com',
        '2XshJmBsZWmSCEmtOdLE'
    ),
(
        339,
        'needfulWasp5',
        'vZOxooN@gmail.com',
        'Yvdbi7aqbKCOHK2q357x'
    ),
(
        344,
        'joyfulSmelt6',
        'VKPuAvu@gmail.com',
        '41l9rD6i6nQ6vfs0hM59'
    ),
(
        347,
        'giddyJaguar2',
        'kjjHakZ@gmail.com',
        'fUBVnA6i8RamS7IwLLOE'
    ),
(
        348,
        'enviousBurritos1',
        'rnFzcfJ@gmail.com',
        '6sBqt56jhaHkVy9RulCf'
    ),
(
        350,
        'jumpyHyena0',
        'WeASXDS@gmail.com',
        'xvxGBGVabmGyFvclAiBP'
    ),
(
        353,
        'emptySwift0',
        'UESciMx@gmail.com',
        'YovOrDwXNCIW4DwBKQcl'
    ),
(
        356,
        'pluckyPolenta5',
        'TaPCmlQ@gmail.com',
        'RafsQ9Ue0bKS1M2FV8Ta'
    ),
(
        357,
        'enragedPorpoise5',
        'jzaFOnz@gmail.com',
        'eika2uYY7VuFavg889Pi'
    ),
(
        361,
        'outlyingDinosaur2',
        'XNWrxIk@gmail.com',
        'SyvAM198J7h2rehopjjV'
    ),
(
        362,
        'grizzledDunbird7',
        'yzuzqjW@gmail.com',
        '5IPODtFbH0z9SEHy1PKs'
    ),
(
        363,
        'stressedPoultry9',
        'bmKxWev@gmail.com',
        'YlnW9W3KiS71R5Cnchq7'
    ),
(
        369,
        'aboardBass2',
        'qtSqXAE@gmail.com',
        'r5aetC4m9QpeosmtOh0P'
    ),
(
        376,
        'aboardRuffs7',
        'XAtzcXy@gmail.com',
        '8mtDmJWcbuATNkzMPJOG'
    ),
(
        379,
        'jumpyRice0',
        'egbKcQt@gmail.com',
        '1vSWlfNWwlWRdoFxBswx'
    ),
(
        381,
        'chicSwift5',
        'ktTvVFz@gmail.com',
        'F3ZSFAlAA9MSIfYHlMRn'
    ),
(
        382,
        'thrilledTeal4',
        'orRCBFB@gmail.com',
        'h3NnG0lifP7S7Rv8AkRN'
    ),
(
        385,
        'superiorHawk3',
        'hhpmtSd@gmail.com',
        'zgvZX75DJEGjMak9Llgi'
    ),
(
        386,
        'aboardOtter3',
        'clCPrVq@gmail.com',
        '8E6j7Yk7vyGMw0LuiJSl'
    ),
(
        398,
        'troubledCod3',
        'djjrjQJ@gmail.com',
        'T1yFeJioHuZi4bpwTTvR'
    ),
(
        406,
        'scornfulPorpoise5',
        'lsAkEZP@gmail.com',
        'Pa8baVZjrWnnqbxInrzD'
    ),
(
        409,
        'wornoutSnail0',
        'uliAnfH@gmail.com',
        '1K9yF2rGfKfiSgwE0Qtt'
    ),
(
        412,
        'mildFalcon1',
        'AOkoiXw@gmail.com',
        'p1n8FGmrR4es7IdFqu4s'
    ),
(
        415,
        'ardentChamois8',
        'HgTTiSc@gmail.com',
        'GOJzN4PxChcWX7q6C1cW'
    ),
(
        424,
        'grudgingMandrill9',
        'bWfzBeH@gmail.com',
        'uC147oTn46MLO190rgDD'
    ),
(
        443,
        'panickySeahorse2',
        'OnjYcIB@gmail.com',
        'o28I7sFuRzHKIlzONipG'
    ),
(
        447,
        'amazedPear7',
        'dodUonf@gmail.com',
        'XcOfdiddaSkCJQz5DGwd'
    ),
(
        448,
        'joyfulCordial9',
        'dyUbkon@gmail.com',
        '3agNmFCqctHiH0053QC1'
    ),
(
        450,
        'mercifulBasmati4',
        'dFwkrFP@gmail.com',
        'k1nJex2PEzxv5VMQZc2G'
    ),
(
        452,
        'artisticBobolink4',
        'NOZsIwa@gmail.com',
        'OlmGQ6MdyzfVmQjP4JOH'
    ),
(
        455,
        'ferventLeopard5',
        'oXVtNap@gmail.com',
        'Df6H95YIlSILwWRnI6hp'
    ),
(
        456,
        'crummyIguana4',
        'FlibGpM@gmail.com',
        '9defcdGZ4TLZIwoeuHge'
    ),
(
        458,
        'yearningWidgeon9',
        'gKnrFRv@gmail.com',
        'FzSIBLJRDMbCuprs5O5l'
    ),
(
        459,
        'pluckyStork0',
        'OFAIDbA@gmail.com',
        'tghMg5n1DHkbxF3XuyL0'
    ),
(
        462,
        'joyfulQuiche5',
        'cftqpkK@gmail.com',
        '1f2BXiJzfn0UDhCR9UWQ'
    ),
(
        465,
        'wearyPonie3',
        'najfPBp@gmail.com',
        'Xo7Sjcr4zeJ3srkKVzG7'
    ),
(
        471,
        'jubilantMussel6',
        'iannIqL@gmail.com',
        'NqyrgkvtIwtdaXqrVe9k'
    ),
(
        473,
        'aloofDove7',
        'sYQayph@gmail.com',
        'y3zne0lC3cGCdGkqv95Z'
    ),
(
        475,
        'relievedPepper8',
        'WywVftI@gmail.com',
        'Nh6eql5yGQxoQXTjJMmN'
    ),
(
        477,
        'insecureIguana2',
        'ovhTFjs@gmail.com',
        'ZCaanlE9oBM34N3BVK0M'
    ),
(
        480,
        'shySausage2',
        'jKMviVe@gmail.com',
        'xpJ5ngd13uGmdUhV9NpA'
    ),
(
        481,
        'excludedTruffle2',
        'GwhxYHS@gmail.com',
        'N4Vkb3rDhcglZTKYZuM5'
    ),
(
        484,
        'wakefulSardines1',
        'leOPuKX@gmail.com',
        'RE6ENQXdiT5mGyCPqxVX'
    ),
(
        486,
        'sincereTacos7',
        'VqkmARP@gmail.com',
        'VgSUVdBxoPF1ecoHomtJ'
    ),
(
        487,
        'brainyBustard3',
        'sFMoiTD@gmail.com',
        'MSXxuvxqPVPNzDVPBOs4'
    ),
(
        489,
        'vengefulGarlic4',
        'apxXRpi@gmail.com',
        'AOvY4V3cQW4htYriOvaW'
    ),
(
        495,
        'curiousCaviar2',
        'tbjMcnO@gmail.com',
        'Enrhl4QjgQLSGSVU8vPI'
    ),
(
        496,
        'stressedDingo7',
        'fUOOqDH@gmail.com',
        'DtkpDF3Uyup7KXQGH7HV'
    );